### PR TITLE
Updates schema to support rollbacks

### PR DESCRIPTION
**Pull request by pbarnum**
This has **NOT** been tested.

For instance, I don't know whether the game will send character IDs when creating a character. I also don't know if the game can call to update a character and still function if the server returns that character with a different ID (though, at that point it wouldn't be an expected PUT request).

Let me know what you think! This is a first pass at versioning characters. I realized now that there probably should have been a join table to keep track of versions. But it was done this way to help preserve the idea that a "Character" can have only 1 identifier. So therefore the latest version is always the first character entry created in the database.

### CODE REVIEW

**Comment by SaintWish** [comment]
The GUID is mainly for the database to use as a unique key. 

Basically when a player joins a server the game server requests the character data for the 3 slots by using this end point ``GET /api/v1/character/<steamid 64>/<slot #>`` then from there the game server uses the GUID to update the the character data using this end point ``PUT /api/v1/character/<GUID>`` if that helps at all.

It wouldn't be all that difficult to change the end points that the game server uses as long as we continue to use the same logic process if you get what I mean.

Anyways, great job and cheers for all of your help :). I'll check out the code today later on and test it out.

**Review by SaintWish — COMMENTED** [review]
Is the ``DepreactedCharacter`` table for the currently use characters, and the ``Character`` table for the stored versions of characters? Also how often or when are the characters backup per se for use with the rollback system?

**Comment by pbarnum** [comment]
Not exactly. the `DeprecatedCharacter` is just a model I needed in order to keep things backwards compatible. As you can see, the model is the exact same as what the `Character` used to be. It did have the unfortunate side affect of creating a database table, something that can be changed into a normal struct, but I figured to keep it as a model as it is treated as such.

Characters and their versions are stored in the `characters` table and have a foreign key linking to a Player.

If we are to follow RESTful practices. A Character could not be updated and expect to have a different identifying ID, therefore the "latest" version of a Character is always the same resource (database record). It will always be "version 1" and use the same identifier. The backup versions will continue to increase over time, but should also delete older versions. This is currently hardcoded to `10` versions.

I think in future versions, this can be expanded to an even better database layout (character versions table instead of handling it within the characters table), new API routes with validations, etc..

**Comment by SaintWish** [comment]
> Not exactly. the `DeprecatedCharacter` is just a model I needed in order to keep things backwards compatible. As you can see, the model is the exact same as what the `Character` used to be. It did have the unfortunate side affect of creating a database table, something that can be changed into a normal struct, but I figured to keep it as a model as it is treated as such.
> 
> Characters and their versions are stored in the `characters` table and have a foreign key linking to a Player.
> 
> If we are to follow RESTful practices. A Character could not be updated and expect to have a different identifying ID, therefore the "latest" version of a Character is always the same resource (database record). It will always be "version 1" and use the same identifier. The backup versions will continue to increase over time, but should also delete older versions. This is currently hardcoded to `10` versions.
> 
> I think in future versions, this can be expanded to an even better database layout (character versions table instead of handling it within the characters table), new API routes with validations, etc..

Ah okay I see, yeah perhaps in the future we can refactor the API routes and such and come up with a better database layout. Cheers, for doing this for us it was a lot of help!

**Pull request merged**
